[versions]
asm = "9.7"
spigot = "1.12.2-R0.1-SNAPSHOT"
shadow = "8.1.1"
patchthebucket = "1.0.0"

[libraries]
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
patchthebucket-api = { module = "net.colourlabs.patchthebucket:patchthebucket-api", version.ref = "patchthebucket" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
